### ISSUE TITLE
Minor mistakes in function HalfTimeAR() and more

### ISSUE THREAD

**Issue by Apeuriox** [sbrstrkkdwmdr/osumodcalculator#1]
Sorry for interrupting, but I found some mistakes in:
1. function HalfTimeAR(ar)
2. function odDT(od)
3. function odHT(od)

1.so basically in function DoubleTimeAR(ar), we have this:
```
function DoubleTimeAR(ar) {
    var ms = ar > 5 ? 200 + (11 - ar) * 100 : 800 + (5 - ar) * 80;
    var newAR;
    if (ms < 300) {
        newAR = 11;
    }
    else if (ms < 1200) {
        newAR = Math.round((11 - (ms - 300) / 150) * 100) / 100;
    }
    else {
        newAR = Math.round((5 - (ms - 1200) / 120) * 100) / 100;
    }
    var arobj = {
        ar: newAR,
        ms: ms
    };
    return arobj;
}
```
while in HalfTimeAR(ar):
```
function HalfTimeAR(ar) {
    var newAR;
    var ogtoms = ar > 5 ? 200 + (11 - ar) * 100 : 800 + (5 - ar) * 80;
    var ms = ogtoms * (4 / 3);
    if (ms < 300) {
        newAR = 11;
    }
    else if (ms < 1200) {
        newAR = Math.round((11 - (ms - 300) / 150) * 100) / 100;
    }
    else {
        newAR = Math.round((5 - (ms - 1200) / 120) * 100) / 100;
    }
    var arobj = {
        ar: newAR,
        ms: ms
    };
    return arobj;
}
```
the difference between these two is that halfTime has 
`var ms = ogtoms * (4 / 3);`
so, actually it calculated the "DTed" value rather than the "Nomod" one. By fixing it, change this line to
`var ms = ogtoms * (4 / 3) * (3 / 4 ); `
which can be simplified as 
`var ms = ogtoms * 2`

2. The next mistake is that the osu! will add 0,33 ms to all OD values after DT calculation while in HT, it's 0.66ms.
[Reddit link about mod Formulas](https://www.reddit.com/r/osugame/comments/6phntt/difficulty_settings_table_with_all_values/)
based on the osu! wiki, OD formula in 300 hit windows is 
`80 - 6 × OD`
Therefore after DT was applied, the hit window should be 80 - 6 × OD+0.33 (ms). when reversing calculating, it will make the OD value a bit higher. 
so in your code:
```
function odDT(od) {
    var range300 = (79 - (od * 6) + 0.5) * 2 / 3;
    var odobj = {
        hitwindow_300: range300,
        hitwindow_100: (139 - (od * 8) + 0.5) * 2 / 3,
        hitwindow_50: (199 - (od * 10) + 0.5) * 2 / 3,
        od_num: parseFloat(((79.5 - range300) / 6).toFixed(2)) > 11 ? 11 : parseFloat(((79.5 - range300) / 6).toFixed(2))
    };
    return odobj;
}
```
change it to:
```
function odDT(od) {
    var range300 = (79 - (od * 6) + 0.5) * 2 / 3;
    var odobj = {
        hitwindow_300: range300,
        hitwindow_100: (139 - (od * 8) + 0.5) * 2 / 3,
        hitwindow_50: (199 - (od * 10) + 0.5) * 2 / 3,
        od_num: parseFloat(((79.66 - range300) / 6).toFixed(2)) > 11 ? 11 : parseFloat(((79.5 - range300) / 6).toFixed(2))
    };
    return odobj;
}
```
same as the odHT <3

**Comment by sbrstrkkdwmdr** [comment]
Thanks for the feedback! 
However, i noticed an error with your first point:
If you change 
` var ms = ogtoms * (4 / 3);` to ` var ms = ogtoms * 2;` it makes the calculation less accurate
going off of [this spreadsheet](https://docs.google.com/spreadsheets/d/1f17denU9Dgdi4xTwQ_Fb-V96GFnYeeRQn4ChEXwJw6I/edit#gid=286995921) and using AR9 as the test value
with `ms*(4/3)` the output is `{ ar: 7.67, ms: 800 }`
but with `ms*2` the output is `{ ar: 5, ms: 1200 }`

I have now implemented the OD changes so thanks for that <3 o/
